apiVersion: apps/v1
kind: Deployment
metadata:
  name: twedds
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twedds
  template:
    metadata:
      labels:
        app: twedds
    spec:
      containers:
      - name: twedds-container
        image: myregistry/twedds:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      imagePullSecrets:
      - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: twedds-service
  namespace: default
spec:
  selector:
    app: twedds
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
