apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiz-brie
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twiz-brie
  template:
    metadata:
      labels:
        app: twiz-brie
    spec:
      containers:
      - name: twiz-brie-container
        image: myregistry/twiz-brie:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: VERTEX_EDGE_URL
          value: http://vertex-edge-service.vertex-edge:8080
        - name: TWEEDS_URL
          value: http://tweeds-service.default:8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      imagePullSecrets:
      - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: twiz-brie-service
  namespace: default
spec:
  selector:
    app: twiz-brie
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
