apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertex-edge-deployment
  namespace: vertex-edge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vertex-edge
  template:
    metadata:
      labels:
        app: vertex-edge
    spec:
      containers:
      - name: vertex-edge-container
        image: tmomtpedge/edgetestlocal:ETSITesting-11790
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      imagePullSecrets:
      - name: vertex-edge-dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vertex-edge-hpa
  namespace: vertex-edge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vertex-edge-deployment
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
