apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::136091176431:user/abgenerette
      username: abgenerette
      groups:
        - system:masters
    - userarn: arn:aws:iam::136091176431:user/tdubois
      username: tdubois
      groups:
        - system:masters
    - userarn: arn:aws:iam::136091176431:user/rngwanah
      username: rngwanah
      groups:
        - system:masters
    - userarn: arn:aws:iam::136091176431:user/eessah
      username: eessah
      groups:
        - system:masters